import { Router } from 'express';

import KindergartenController from '../controllers/kindergartenController.js';

const router = Router();

router.get('/', KindergartenController.getAll);
router.get('/menus/all', KindergartenController.getMenus);
router.get('/menus/compliance-statistics', KindergartenController.getMenuComplianceStatistics);
router.get('/dishes/all', KindergartenController.getDishes);
router.get('/medical-stock-alerts', KindergartenController.getMedicalStockAlerts);
router.get('/alerts', KindergartenController.getAlerts);
router.get('/ai-insights', KindergartenController.getAIInsights);
router.get('/websites', KindergartenController.getWebsites);
router.get('/websites/:kindergartenId', KindergartenController.getWebsiteByKindergarten);
router.put('/websites/:kindergartenId', KindergartenController.saveWebsite);
router.get('/parent-profile-news', KindergartenController.getParentProfileNews);
router.post('/parent-profile-news', KindergartenController.createParentProfileNews);
router.put('/parent-profile-news/:newsId', KindergartenController.updateParentProfileNews);
router.delete('/parent-profile-news/:newsId', KindergartenController.deleteParentProfileNews);
router.get('/websites/:kindergartenId/news', KindergartenController.getWebsiteNews);
router.post('/websites/:kindergartenId/news', KindergartenController.createWebsiteNews);
router.get('/website-news', KindergartenController.getWebsiteNews);
router.put('/website-news/:newsId', KindergartenController.updateWebsiteNews);
router.delete('/website-news/:newsId', KindergartenController.deleteWebsiteNews);
router.get('/advertisements', KindergartenController.getAdvertisements);
router.post('/advertisements', KindergartenController.createAdvertisement);
router.put('/advertisements/:adId', KindergartenController.updateAdvertisement);
router.delete('/advertisements/:adId', KindergartenController.deleteAdvertisement);
router.get('/inspections', KindergartenController.getInspections);
router.get('/inspections/:id/word', KindergartenController.downloadInspectionWord);
router.post('/inspections', KindergartenController.createInspection);
router.post('/dish-items/analyze-page', KindergartenController.analyzeDishPage);
router.post('/dish-items', KindergartenController.createDish);
router.put('/dish-items/:id', KindergartenController.updateDish);
router.delete('/dish-items/:id', KindergartenController.deleteDish);
router.post('/dishes', KindergartenController.createDish);
router.put('/dishes/:id', KindergartenController.updateDish);
router.delete('/dishes/:id', KindergartenController.deleteDish);
router.post('/menus/ten-day', KindergartenController.createTenDayMenus);
router.get('/daily-district-expenses', KindergartenController.getDailyDistrictExpenses);
router.post('/daily-district-expenses', KindergartenController.saveDailyDistrictExpenses);
router.get('/district-warehouse-purchases', KindergartenController.getDistrictWarehousePurchases);
router.post('/district-warehouse-purchases', KindergartenController.saveDistrictWarehousePurchases);
router.get('/:id', KindergartenController.getById);
router.post('/', KindergartenController.create);
router.put('/:id', KindergartenController.update);
router.delete('/:id', KindergartenController.delete);

export default router;
